plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

loom {
	splitEnvironmentSourceSets()

	accessWidenerPath = file("src/main/resources/slotplus.accesswidener")

	mods {
		"slotplus" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

repositories {
	maven {
		name = "Terraformers"
		url = "https://maven.terraformersmc.com/"
	}
	maven {
		name = "Xander Maven"
		url = "https://maven.isxander.dev/releases"
	}
	mavenCentral()
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
	implementation "dev.isxander:yet-another-config-lib:${project.yacl_version}"
	implementation "com.terraformersmc:modmenu:${project.modmenu_version}"
}

def modVersion = project.version.toString()

tasks.withType(ProcessResources).configureEach {
	inputs.property "version", modVersion

	filesMatching("fabric.mod.json") {
		expand "version": modVersion
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
	it.options.encoding = "UTF-8"
}

java {
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	archiveVersion = "${project.version}-fabric-mc${project.minecraft_version}"
	def projectName = project.name
	inputs.property "projectName", projectName
	from("LICENSE") {
		rename { "${it}_$projectName"}
	}
}
